### ISSUE TITLE
Error executing process > 'POREC:pairsToCooler (343)'

### ISSUE THREAD

**Issue by CarolinaA09** [epi2me-labs/pore-c-py#12]
Hello,

I am trying to run pore-c on an HPC with this configuration: 

srun -t 5:00:00 -p interact -N 1 -n 4 --x11=first --pty /bin/bash

But I get the Error executing process > 'POREC:pairsToCooler (343)'. Is it possible you could help me figure out what this error means? This is the output from the report.html:

_The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:

Error executing process > 'POREC:pairsToCooler (343)'

Caused by:
  Process `POREC:pairsToCooler (343)` terminated with an error exit status (1)

Command executed:

  cooler cload pairs -c1 2 -p1 3 -c2 4 -p2 5 fasta.fai:1000 20240605_Dicanthelium_clandestinum_PoreC.pairs.gz 20240605_Dicanthelium_clandestinum_PoreC.pairs.cool

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  INFO:cooler.create:Writing chunk 0: tmpvh6hmtk8.multi.cool::0
  INFO:cooler.create:Creating cooler at "tmpvh6hmtk8.multi.cool::/0"
  INFO:cooler.create:Writing chroms
  INFO:cooler.create:Writing bins
  INFO:cooler.create:Writing pixels
  INFO:cooler.create:Writing indexes
  INFO:cooler.create:Writing info
  INFO:cooler.create:Merging into 20240605_Dicanthelium_clandestinum_PoreC.pairs.cool
  INFO:cooler.create:Creating cooler at "20240605_Dicanthelium_clandestinum_PoreC.pairs.cool::/"
  INFO:cooler.create:Writing chroms
  INFO:cooler.create:Writing bins
  INFO:cooler.create:Writing pixels
  INFO:cooler.reduce:nnzs: [0]
  INFO:cooler.reduce:current: [0]
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/cooler", line 10, in 
      sys.exit(cli())
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/cli/cload.py", line 584, in pairs
      create_cooler(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/create/_create.py", line 1038, in create_cooler
      create_from_unordered(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/create/_create.py", line 763, in create_from_unordered
      create(cool_uri, bins, chunks, columns=columns, dtypes=dtypes, mode=mode, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/create/_create.py", line 641, in create
      nnz, ncontacts = write_pixels(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/create/_create.py", line 211, in write_pixels
      for i, chunk in enumerate(iterable):
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/reduce.py", line 151, in __iter__
      combined = pd.concat(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
      return func(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 368, in concat
      op = _Concatenator(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 425, in __init__
      raise ValueError("No objects to concatenate")
  ValueError: No objects to concatenate

Work dir:
  /work/users/c/a/caroe/Bean_assembly_pipeline/Pore_C/work/cd/be215579d8c059117271446e642b22

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line_

**Comment by sarahjeeeze** [comment]
Hi, i responded to this message over on wf-pore-c repo https://github.com/epi2me-labs/wf-pore-c/issues/78

**Comment by sarahjeeeze** [comment]
Closing as discussion also on linked issue
